"""Initial persistence schema

Revision ID: fe8d4da69afa
Revises: 
Create Date: 2026-09-05 17:21:02.454645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = 'fe8d4da69afa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SEED_USER_ID = "00000000-0000-4000-8000-000000000001"
SEED_USER_EMAIL = "local@reflect.invalid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'taken_on', 'instrument', name='uq_checkin_per_day')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index('ix_checkins_user_taken', ['user_id', 'taken_on'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('fused_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_confidence', sa.Float(), nullable=False),
    sa.Column('attenuation', sa.Float(), nullable=False),
    sa.Column('max_divergence', sa.Float(), nullable=True),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.CheckConstraint("label IN ('anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise')", name='ck_fused_label'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fused_readings', schema=None) as batch_op:
        batch_op.create_index('ix_fused_session_t', ['session_id', 't'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.CheckConstraint("channel IN ('face', 'text', 'voice')", name='ck_readings_channel'),
    sa.CheckConstraint("label IN ('anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise')", name='ck_readings_label'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_session_t', ['session_id', 't'], unique=False)

    op.create_table('session_summaries',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('n_readings', sa.Integer(), nullable=False),
    sa.Column('n_fused_readings', sa.Integer(), nullable=False),
    sa.Column('mean_valence', sa.Float(), nullable=True),
    sa.Column('conflict_rate', sa.Float(), nullable=True),
    sa.Column('dominant_label', sa.String(length=16), nullable=True),
    sa.Column('channel_counts', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


    # Auth is deferred, so seed the one local user every session attaches to.
    # user_id exists from this first migration, so real accounts later are a
    # change to how the user is resolved, not a schema migration.
    op.bulk_insert(
        sa.table(
            "users",
            sa.column("id", sa.String),
            sa.column("email", sa.String),
            sa.column("password_hash", sa.String),
            sa.column("created_at", sa.DateTime),
        ),
        [
            {
                "id": SEED_USER_ID,
                "email": SEED_USER_EMAIL,
                "password_hash": None,
                "created_at": datetime.now(timezone.utc),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_summaries')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index('ix_readings_session_t')

    op.drop_table('readings')
    with op.batch_alter_table('fused_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_fused_session_t')

    op.drop_table('fused_readings')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_started')

    op.drop_table('sessions')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index('ix_checkins_user_taken')

    op.drop_table('checkins')
    op.drop_table('users')
    # ### end Alembic commands ###
